const hqFields = <String, Map<String, String>>{
  'shoe': {
    'shoe_id': '상품 ID',
    'brand_name': '상품명',
    'shoe_price': '가격',
    'stock_quantity': '재고 수량',
    'standard_stock': '기준 재고',
  },
  'purchase': {
    'purchase_id': '주문 ID',
    'shoe_shoe_id': '상품',
    'user_user_id': '고객',
    'quantity': '수량',
    'sale_price': '판매 단가',
    'payment_id': '결제 ID',
  },
  'shipment': {
    'shipment_id': '배송 ID',
    'shoe_shoe_id': '상품',
    'store_store_id': '대리점',
    'delivery_quantity': '배송 수량',
    'delivery_status': '배송 상태',
  },
  'receive': {
    'receive_id': '수령 ID',
    'store_store_id': '대리점',
    'user_user_id': '고객',
    'receive_quantity': '수령 수량',
    'receive_date': '수령일',
    'receive_status': '수령 상태',
  },
  'return_record': {
    'return_id': '반품 ID',
    'shoe_shoe_id': '상품',
    'employee_employee_id': '담당 직원',
    'return_date': '반품일',
  },
  'approval': {
    'approval_id': '품의 ID',
    'approval_name': '품의명',
    'approval_content': '내용',
  },
  'approval_process': {
    'approval_process_id': '결재 ID',
    'approval_approval_id': '품의',
    'employee_employee_id': '담당 직원',
    'approval_status': '결재 상태',
    'team_leader_approval': '팀장 결재',
    'director_approval': '이사 결재',
    'processed_at': '처리일',
  },
  'purchase_order': {
    'order_id': '발주 ID',
    'shoe_shoe_id': '상품',
    'shoe_manufacturer_manufacturer_id': '제조사',
    'order_quantity': '발주 수량',
    'get_amount': '발주 금액',
    'order_date': '발주일',
  },
  'get_order': {
    'get_order_id': '수주 ID',
    'shoe_shoe_id': '상품',
    'shoe_manufacturer_manufacturer_id': '제조사',
    'get_order_quantity': '수량',
    'get_order_date': '일자',
  },
  'payment': {
    'payment_id': '결제 ID',
    'user_user_id': '고객',
    'payment_amount': '결제 금액',
    'payment_status': '결제 상태 코드',
    'payment_date': '결제일',
  },
  'user': {
    'user_id': '사용자 ID',
    'user_name': '이름',
    'user_email': '이메일',
    'user_phone': '전화번호',
    'join_date': '가입일',
  },
  'employee': {
    'employee_id': '직원 ID',
    'employee_name': '이름',
    'employee_department': '부서',
    'employee_position': '직급',
  },
  'store': {
    'store_id': '대리점 ID',
    'agency_name': '대리점명',
    'district_name': '지역',
    'phone': '전화번호',
    'latitude': '위도',
    'longitude': '경도',
  },
  'shoe_manufacturer': {
    'manufacturer_id': '제조사 ID',
    'manufacturer_name': '제조사명',
  },
};
